Repository dscpesu/SimpleML, pull requests merged in 2023-10, with the labels that each got.

#2 Changed README
  README.md
Labels: good first issue, hacktoberfest

#4 Added Project Files
  Amazon Reviews Sentiment Analysis/Dataset/README.md
  Amazon Reviews Sentiment Analysis/Images/newplot.png
  Amazon Reviews Sentiment Analysis/Images/result.png
  Amazon Reviews Sentiment Analysis/Model/README.md
  Amazon Reviews Sentiment Analysis/Model/amazon-reviews-sentiment-analysis.ipynb
  Amazon Reviews Sentiment Analysis/requirements.txt
  American Sign Language Detection/README.md
  American Sign Language Detection/dataset/readme.md
  American Sign Language Detection/images/image.png
  American Sign Language Detection/images/predicted labels.png
  American Sign Language Detection/images/readme.md
  American Sign Language Detection/images/visualized images.png
  American Sign Language Detection/models/InceptionResNetV2(88%).ipynb
  American Sign Language Detection/models/InceptionV3(88%).ipynb
  American Sign Language Detection/models/MobileNet(97%).ipynb
  American Sign Language Detection/models/VGG16(97%).ipynb
  American Sign Language Detection/models/readme.md
  Bank Loan Approval Prediction/Dataset/UniversalBank.csv
  Bank Loan Approval Prediction/Images/Age.png
  Bank Loan Approval Prediction/Images/Approved_Not_Approved.png
  Bank Loan Approval Prediction/Images/Average CC Spending.png
  Bank Loan Approval Prediction/Images/Heatmap.png
  Bank Loan Approval Prediction/Images/Personal loans.png
  Bank Loan Approval Prediction/Images/conf_matrix.png
  Bank Loan Approval Prediction/Images/income.png
  Bank Loan Approval Prediction/Images/modelloss.png
  Bank Loan Approval Prediction/Model/README.md
  Bank Loan Approval Prediction/Model/bank-loan-approval-using-AI.ipynb
  Bank Loan Approval Prediction/README.md
  Bank Loan Approval Prediction/requirements.txt
  Urdu_Text_Detection/Dataset/README.md
  Urdu_Text_Detection/Images/CNN_architecture.png
  Urdu_Text_Detection/Images/adadelta_acc.png
  Urdu_Text_Detection/Images/adadelta_loss.png
  Urdu_Text_Detection/Images/adagrad_acc.png
  Urdu_Text_Detection/Images/adagrad_loss.png
  Urdu_Text_Detection/Images/adam_acc.png
  Urdu_Text_Detection/Images/adam_loss.png
  Urdu_Text_Detection/Images/aggregated_data.png
  Urdu_Text_Detection/Images/output_samples.png
  Urdu_Text_Detection/Images/performance_measure.png
  Urdu_Text_Detection/Images/sgd_acc.png
  Urdu_Text_Detection/Images/sgd_loss.png
  Urdu_Text_Detection/Images/testing_data.png
  Urdu_Text_Detection/Images/training_data.png
  Urdu_Text_Detection/Images/training_samples.png
  Urdu_Text_Detection/Model/README.md
  Urdu_Text_Detection/Model/urdu-text-detection.ipynb
  Urdu_Text_Detection/requirements.txt
  Yahoo Answers NLP/Dataset/README.md
  Yahoo Answers NLP/Images/CNN Plot.png
  Yahoo Answers NLP/Images/LSTM Plot.png
  Yahoo Answers NLP/Images/box plot.png
  Yahoo Answers NLP/Images/yahoo-answers.png
  Yahoo Answers NLP/Model/Yahoo_Answers_NLP.ipynb
  Yahoo Answers NLP/README.md
  Yahoo Answers NLP/requirements.txt
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#20 added an src folder, Aug and instructions
  American Sign Language Detection/src/Augementation.py
  American Sign Language Detection/src/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#22 EDA and correlation analysis
  Bank Loan Approval Prediction/Model/BankLoan_EDA.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#29 American Sign Language Issue #14
  American Sign Language Detection/models/American_Sign_Language_MobileNet(96).ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#30 This is a basic implementation of QA model using BERT.
  .gitignore
  Yahoo Answers NLP/Dataset/classes.txt
  Yahoo Answers NLP/Dataset/readme.txt
  Yahoo Answers NLP/bert_model.ipynb
  Yahoo Answers NLP/requirements.txt
Labels: hacktoberfest, hacktoberfest-accepted

#31 interactive python trainer code + plots
  American Sign Language Detection/images/plots/inceptionv3_plot.png
  American Sign Language Detection/images/plots/mobilenet_plot.png
  American Sign Language Detection/images/plots/vgg16_plot.png
  American Sign Language Detection/src/trainer.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#32 Student Academic Performance Analysis
  Student Academic Performace Analysis/Images/address_distribution.png
  Student Academic Performace Analysis/Images/age_distribution.png
  Student Academic Performace Analysis/Images/failures_distribution.png
  Student Academic Performace Analysis/Images/family_size_distribution.png
  Student Academic Performace Analysis/Images/father_education_distribution.png
  Student Academic Performace Analysis/Images/father_job_distribution.png
  Student Academic Performace Analysis/Images/gender.png
  Student Academic Performace Analysis/Images/mother_education_distribution.png
  Student Academic Performace Analysis/Images/mother_job_distribution.png
  Student Academic Performace Analysis/Images/parent_cohabitation_status_distribution.png
  Student Academic Performace Analysis/Images/reason_for_choosing_school_distribution.png
  Student Academic Performace Analysis/Images/school.png
  Student Academic Performace Analysis/Images/sex_distribution.png
  Student Academic Performace Analysis/Images/study_time_distribution.png
  Student Academic Performace Analysis/Images/travel_time_distribution.png
  Student Academic Performace Analysis/Model/model.ipynb
  Student Academic Performace Analysis/README.md
  Student Academic Performace Analysis/Streamlit/app.py
  Student Academic Performace Analysis/Streamlit/model.pkl
  Student Academic Performace Analysis/data/student_data.csv
  Student Academic Performace Analysis/requirements.txt
  Student Academic Performace Analysis/schema/dataframe_schema.csv
Labels: hacktoberfest, hacktoberfest-accepted

#34 Added ClassificationModels.ipynb
  Bank Loan Approval Prediction/Images/Heatmap.png
  Bank Loan Approval Prediction/Model/ClassificationModels.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added Heatmap.png
  Bank Loan Approval Prediction/Images/Heatmap.png
Labels: hacktoberfest, hacktoberfest-accepted

#38 added ModelsComparison.md
  Bank Loan Approval Prediction/Model/ModelsComparison.md
Labels: hacktoberfest, hacktoberfest-accepted

#40 added vis
  Yahoo Answers NLP/visualize.ipynb
Labels: hacktoberfest, hacktoberfest-accepted
